config/routes.rb
Rails.application.routes.draw do

  devise_for :employees, :controllers => { registrations: 'registrations' }

  root to: "home#index"

  resources :boats, :jobs, :assignments

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :boats
  belongs_to :jobs

end

app/models/boat.rb
class Boat < ApplicationRecord
  has_many :assignments
  has_many :jobs, through: :assignments
  
  validates :name, uniqueness: true
  validates :containers, numericality: true
end

app/models/employee.rb
class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/job.rb
class Job < ApplicationRecord
  has_many :assignments
  has_many :boats, through: :assignments

  validates :name, uniqueness: true
  validates :containers, numericality: true
  validates :cost, numericality: {greater_than: 1000}
  validates :description, length: {minimum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  def index
    @boats = Boat.all
    @jobs = Job.all
  end


  def new
    @boats = Boat.all
    @jobs = Job.all
    @assignment = Assignment.new
  end


  def create
    @boats = Boat.all
    @jobs = Job.all

    @boat = Boat.find(params[:boat][:id])
    @job = Job.find(params[:job][:id])

    @assignment = Assignment.create(
      @boat, @job
    )

    if @assignment.save
      redirect_to assignments_path
    else
      render new_assignment_path
    end
  end


  def show
  end


  def edit
  end


  def update
  end


  def destroy
  end

  # private
  # def params_assignments
  #   params.require(:assignment).permit(:name, :description, :containers, :cost, :origin, :destination)
  # end

end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController

  def new
    @boat = Boat.all
  end


  def new
    @boat = Boat.new
  end


  def create
    @boat = Boat.new(
      params_boat
    )

    if @boat.save
      redirect_to boat_path(@boat)
      # boat_path(@boat) same as /boats/#{@boat.id}
    else
      render new_boat_path
    end
  end


  def show
    @boat = Boat.find(params[:id])
  end


  def edit
    @boat = Boat.find(params[:id])
  end


  def update
    @boat = Boat.find(params[:id])

    @boat.update(
      params_boat
    )

    if @boat.save
      redirect_to boat_path(@boat)
      # boat_path(@boat) same as /boats/#{@boat.id}
    else
      render edit_boat_path
    end
  end


  def destroy
  end

  private
  def params_jobs
    params.require(:boat).permit(:name, :containers, :location)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def new
    @job = Job.new
  end


  def create
    @job = Job.new(
      params_jobs
    )

    @job.save

    if @job.save
      redirect_to job_path(@job)
      # job_path(@job) same as /jobs/#{@job.id}
    else
      render new_job_path
    end
  end


  def show
    @job = Job.find(params[:id])
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])

    @job.update(
      params_jobs
    )

    if @job.save
      redirect_to job_path(@job)
      # job_path(@job) same as /jobs/#{@job.id}
    else
      render edit_job_path
    end
  end


  def destroy
  end

  private
  def params_jobs
    params.require(:job).permit(:name, :description, :containers, :cost, :origin, :destination)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:employee).permit(:first_name, :last_name, :bio, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:employee).permit(:first_name, :last_name, :bio, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/boats_helper.rb
module BoatsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
  
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/assignments/_assign_form.html.erb
    <%= form_for @assignment do |f| %>

        <%= f.label "Job: ", html: {class: "formLabel"} %>
        <!-- job drop down -->
        <%= f.select(:job_id, @jobs.collect {|j| [j.name, j.id]} ) %><br> <br>

        <%= f.label "Boat: ", html: {class: "formLabel"} %>
        <!-- boats drop down -->
        <%= f.select(:boat_id, @boats.collect {|b| [b.name, b.id]} ) %><br> <br>

        <%= f.submit "assign", html: {id: "assignFormBtn", class: "btn"} %>

    <% end %>

app/views/assignments/edit.html.erb
<div class="contentContainer">
  <h1>Edit Assignment</h1>

  <%= render "assign_form" %>
</div>

app/views/assignments/index.html.erb
<div class="contentContainer">
  <h1>This page will list all jobs and boats + assignments</h1>
</div>

app/views/assignments/new.html.erb
<div class="contentContainer">
  <h1>Set Assignments</h1>

  <%= render "assign_form" %>
</div>

app/views/boats/_boat_errors.html.erb
<% if @boat.errors.full_messages.any? %>
  <ul>
    <% @boat.errors.full_messages.each do |error_message| %>
      <li><%= error_message %></li> <br />
    <% end %>
  </ul>
<% end %>

app/views/boats/_boat_form.html.erb
<%= form_for @boat do |f| %>

          <%= f.label :name, html: {class: "formLabel"} %>
          <%= f.text_field :name, autofocus: true %><br> <br>

          <%= f.label :containers, html: {class: "formLabel"} %>
          <%= f.text_field :containers %><br> <br>

          <%= f.label :location, html: {class: "formLabel"} %>
          <%= f.select(:location, ["Bahamas", "Canada", "Chile", "Jamaica", "Mexico", "New York", "North Carolina"]) %><br> <br>

          <%= f.submit html: {id: "boatFormBtn", class: "btn"} %>

        <% end %>

app/views/boats/edit.html.erb
<div class="contentContainer">
  <%= render "boat_errors" %>

  <h1>Edit Boat</h1>

  <%= render "boat_form" %>

</div>

app/views/boats/new.html.erb
<div class="contentContainer">
  <%= render "boat_errors" %>

  <h1>Add a Ship</h1>

  <%= render "boat_form" %>

</div>

app/views/boats/show.html.erb
<div class="contentContainer">
  <h1>Boats#show</h1>
  <p>Find me in app/views/boats/show.html.erb</p>

</div>

app/views/home/index.html.erb
<div class="contentContainer">

  <!-- <div class="logo">
    <%= image_tag('anchorLogo.jpg', size: '100x100', alt: 'Anchor Logo') %>
  </div> -->

  <div class="mainHeading">
    <h1>Welcome to the Shipyard</h1>
  </div>

  
  <p class="navbar-text pull-right">
  <% if employee_signed_in? %>
    Logged in as <strong><%= current_employee.email %></strong>.
    <%= link_to 'Edit profile', edit_employee_registration_path, :class => 'navbar-link' %> |
    <%= link_to "Logout", destroy_employee_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
  <div class="homeBtns">
    <%= form_tag("/employees/sign_in", :method => :get) do %>
      <%= submit_tag "login", class: "btn", id: "hb1"%>
    <% end %>

    <%= form_tag("/employees/sign_up", :method => :get) do %>
      <%= submit_tag "sign up", class: "btn", id: "hb2"%>
    <% end %>
  </div>
  <% end %>
  </p>

</div>

app/views/jobs/_job_errors.html.erb
<% if @job.errors.full_messages.any? %>
  <ul>
    <% @job.errors.full_messages.each do |error_message| %>
      <li><%= error_message %></li> <br />
    <% end %>
  </ul>
<% end %>

app/views/jobs/_job_form.html.erb
<%= form_for @job do |f| %>

          <%= f.label :name, html: {class: "formLabel"} %>
          <%= f.text_field :name, autofocus: true %><br> <br>

          <%= f.label :description, html: {class: "formLabel"} %>
          <%= f.text_field :description %><br> <br>

          <%= f.label :containers, html: {class: "formLabel"} %>
          <%= f.text_field :containers %><br> <br>

          <%= f.label :cost, html: {class: "formLabel"} %>
          <span>$ &nbsp;</span><%= f.text_field :cost %><br> <br>

          <%= f.label :origin, html: {class: "formLabel"} %>
          <%= f.select(:origin, ["Bahamas", "Canada", "Chile", "Jamaica", "Mexico", "New York", "North Carolina"]) %><br> <br>

          <%= f.label :destination, html: {class: "formLabel"} %>
          <%= f.select(:destination, ["Bahamas", "Canada", "Chile", "Jamaica", "Mexico", "New York", "North Carolina"]) %><br> <br>

          <%= f.submit html: {id: "jobFormBtn", class: "btn"} %>

        <% end %>

app/views/jobs/edit.html.erb
<div class="contentContainer">
  <%= render "job_errors" %>

  <h1>Revise Job</h1>

  <%= render "job_form" %>

</div>

app/views/jobs/new.html.erb
<div class="contentContainer">
  <%= render "job_errors" %>

  <h1>Add a Job</h1>

  <%= render "job_form" %>
</div>

app/views/jobs/show.html.erb
<div class="contentContainer">

  <h1>Jobs#show</h1>
  
  <p>Find me in app/views/jobs/show.html.erb</p>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shipped</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Love+Ya+Like+A+Sister|Open+Sans" rel="stylesheet">

  </head>

  <body>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>




    <%= yield %>


  </body>
</html>